apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  labels:
    app: nginx
data:
  index.html: |
    <html>
      <head>
        <title>dev</title>
      </head>
      <body>
        <h1>dev</h1>
      </body>
    </html>